eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8500
spring:
  cloud:
    config:
      label: master # ≈‰÷√≤÷ø‚µƒ∑÷÷ß
      server:
        git:
          uri: https://gitee.com/lzz54/commnow
          searchPaths: commnow-config
          username: lzz54
          password: Commnow2016
  application:
    name: commnow-config-server